/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DocsDocsLayoutImport } from './routes/docs/_docs-layout'
import { Route as DocsDocsLayoutIndexImport } from './routes/docs/_docs-layout/index'
import { Route as DocsDocsLayoutLicensingIndexImport } from './routes/docs/_docs-layout/licensing/index'
import { Route as DocsDocsLayoutLicensingSustainableUseLicenseImport } from './routes/docs/_docs-layout/licensing/sustainable-use-license'

// Create Virtual Routes

const DocsImport = createFileRoute('/docs')()

// Create/Update Routes

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsDocsLayoutRoute = DocsDocsLayoutImport.update({
  id: '/_docs-layout',
  getParentRoute: () => DocsRoute,
} as any)

const DocsDocsLayoutIndexRoute = DocsDocsLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsDocsLayoutRoute,
} as any)

const DocsDocsLayoutLicensingIndexRoute =
  DocsDocsLayoutLicensingIndexImport.update({
    id: '/licensing/',
    path: '/licensing/',
    getParentRoute: () => DocsDocsLayoutRoute,
  } as any)

const DocsDocsLayoutLicensingSustainableUseLicenseRoute =
  DocsDocsLayoutLicensingSustainableUseLicenseImport.update({
    id: '/licensing/sustainable-use-license',
    path: '/licensing/sustainable-use-license',
    getParentRoute: () => DocsDocsLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/docs/_docs-layout': {
      id: '/docs/_docs-layout'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsLayoutImport
      parentRoute: typeof DocsRoute
    }
    '/docs/_docs-layout/': {
      id: '/docs/_docs-layout/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsDocsLayoutIndexImport
      parentRoute: typeof DocsDocsLayoutImport
    }
    '/docs/_docs-layout/licensing/sustainable-use-license': {
      id: '/docs/_docs-layout/licensing/sustainable-use-license'
      path: '/licensing/sustainable-use-license'
      fullPath: '/docs/licensing/sustainable-use-license'
      preLoaderRoute: typeof DocsDocsLayoutLicensingSustainableUseLicenseImport
      parentRoute: typeof DocsDocsLayoutImport
    }
    '/docs/_docs-layout/licensing/': {
      id: '/docs/_docs-layout/licensing/'
      path: '/licensing'
      fullPath: '/docs/licensing'
      preLoaderRoute: typeof DocsDocsLayoutLicensingIndexImport
      parentRoute: typeof DocsDocsLayoutImport
    }
  }
}

// Create and export the route tree

interface DocsDocsLayoutRouteChildren {
  DocsDocsLayoutIndexRoute: typeof DocsDocsLayoutIndexRoute
  DocsDocsLayoutLicensingSustainableUseLicenseRoute: typeof DocsDocsLayoutLicensingSustainableUseLicenseRoute
  DocsDocsLayoutLicensingIndexRoute: typeof DocsDocsLayoutLicensingIndexRoute
}

const DocsDocsLayoutRouteChildren: DocsDocsLayoutRouteChildren = {
  DocsDocsLayoutIndexRoute: DocsDocsLayoutIndexRoute,
  DocsDocsLayoutLicensingSustainableUseLicenseRoute:
    DocsDocsLayoutLicensingSustainableUseLicenseRoute,
  DocsDocsLayoutLicensingIndexRoute: DocsDocsLayoutLicensingIndexRoute,
}

const DocsDocsLayoutRouteWithChildren = DocsDocsLayoutRoute._addFileChildren(
  DocsDocsLayoutRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsLayoutRoute: typeof DocsDocsLayoutRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsLayoutRoute: DocsDocsLayoutRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsLayoutRouteWithChildren
  '/docs/': typeof DocsDocsLayoutIndexRoute
  '/docs/licensing/sustainable-use-license': typeof DocsDocsLayoutLicensingSustainableUseLicenseRoute
  '/docs/licensing': typeof DocsDocsLayoutLicensingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsLayoutIndexRoute
  '/docs/licensing/sustainable-use-license': typeof DocsDocsLayoutLicensingSustainableUseLicenseRoute
  '/docs/licensing': typeof DocsDocsLayoutLicensingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/_docs-layout': typeof DocsDocsLayoutRouteWithChildren
  '/docs/_docs-layout/': typeof DocsDocsLayoutIndexRoute
  '/docs/_docs-layout/licensing/sustainable-use-license': typeof DocsDocsLayoutLicensingSustainableUseLicenseRoute
  '/docs/_docs-layout/licensing/': typeof DocsDocsLayoutLicensingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/licensing/sustainable-use-license'
    | '/docs/licensing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/licensing/sustainable-use-license'
    | '/docs/licensing'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/_docs-layout'
    | '/docs/_docs-layout/'
    | '/docs/_docs-layout/licensing/sustainable-use-license'
    | '/docs/_docs-layout/licensing/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/docs": {
      "filePath": "docs",
      "children": [
        "/docs/_docs-layout"
      ]
    },
    "/docs/_docs-layout": {
      "filePath": "docs/_docs-layout.tsx",
      "parent": "/docs",
      "children": [
        "/docs/_docs-layout/",
        "/docs/_docs-layout/licensing/sustainable-use-license",
        "/docs/_docs-layout/licensing/"
      ]
    },
    "/docs/_docs-layout/": {
      "filePath": "docs/_docs-layout/index.tsx",
      "parent": "/docs/_docs-layout"
    },
    "/docs/_docs-layout/licensing/sustainable-use-license": {
      "filePath": "docs/_docs-layout/licensing/sustainable-use-license.tsx",
      "parent": "/docs/_docs-layout"
    },
    "/docs/_docs-layout/licensing/": {
      "filePath": "docs/_docs-layout/licensing/index.tsx",
      "parent": "/docs/_docs-layout"
    }
  }
}
ROUTE_MANIFEST_END */
